# Generated by Django 5.0.1 on 2024-01-24 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_material', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('valor_produto', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Orçamento')),
                ('imagem_produto', models.ImageField(blank=True, max_length=250, null=True, upload_to='produtos/')),
                ('descricao_produto', models.TextField()),
                ('categoria_produto', models.CharField(choices=[('Jazigos e jardineiras', 'Jazigos e jardineiras'), ('Fotos em porcelana', 'Fotos em porcelana'), ('Outros serviços', 'Outros serviços')], max_length=100)),
                ('material_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marmoaria.material')),
            ],
        ),
    ]
